// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8V0yOiZUPzijhuvdiqCXb26EPRUaxQQ',
    appId: '1:319920071303:web:2396c73856f1636aed4e22',
    messagingSenderId: '319920071303',
    projectId: 'dr-h-and-co-crm',
    authDomain: 'dr-h-and-co-crm.firebaseapp.com',
    storageBucket: 'dr-h-and-co-crm.appspot.com',
    measurementId: 'G-SZJ9RGZFYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPqt0lbe25ZX-Rz8vRdpxIjxtCcX_U14',
    appId: '1:319920071303:android:b922b6792957b728ed4e22',
    messagingSenderId: '319920071303',
    projectId: 'dr-h-and-co-crm',
    storageBucket: 'dr-h-and-co-crm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHA9eURpiRJrOlkPa3tz5c-8qSQ-jV3c4',
    appId: '1:319920071303:ios:a93a1c26cb99a5faed4e22',
    messagingSenderId: '319920071303',
    projectId: 'dr-h-and-co-crm',
    storageBucket: 'dr-h-and-co-crm.appspot.com',
    androidClientId: '319920071303-fg75lgs9rt3vaurfuulvin04fl0etplb.apps.googleusercontent.com',
    iosClientId: '319920071303-fnq4j7g15qhhg6rng0nkot5s54dcmeo3.apps.googleusercontent.com',
    iosBundleId: 'com.holisticdentalformulas.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHA9eURpiRJrOlkPa3tz5c-8qSQ-jV3c4',
    appId: '1:319920071303:ios:5a960cdb3c60f484ed4e22',
    messagingSenderId: '319920071303',
    projectId: 'dr-h-and-co-crm',
    storageBucket: 'dr-h-and-co-crm.appspot.com',
    androidClientId: '319920071303-fg75lgs9rt3vaurfuulvin04fl0etplb.apps.googleusercontent.com',
    iosClientId: '319920071303-fnq4j7g15qhhg6rng0nkot5s54dcmeo3.apps.googleusercontent.com',
    iosBundleId: 'com.holisticdentalformulas.admin',
  );
}
